version: '3.8'

services:
  # Client Server (Node.js)
  client-server:
    build:
      context: ./client_server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - AI_SERVER_URL=http://ai-server:8000
      - APPWRITE_ENDPOINT=${APPWRITE_ENDPOINT}
      - APPWRITE_PROJECT_ID=${APPWRITE_PROJECT_ID}
      - APPWRITE_API_KEY=${APPWRITE_API_KEY}
    volumes:
      - ./client_server:/app
      - /app/node_modules
    depends_on:
      - ai-server

  # AI Server (Python)
  ai-server:
    build:
      context: ./ai_server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - PORT=8000
      - APPWRITE_ENDPOINT=${APPWRITE_ENDPOINT}
      - APPWRITE_PROJECT_ID=${APPWRITE_PROJECT_ID}
      - APPWRITE_API_KEY=${APPWRITE_API_KEY}
    volumes:
      - ./ai_server:/app
      - ./models:/app/models/weights
