"""
Setup script to prepare the data directory and ensure all required files exist
"""
import os
from pathlib import Path

# Create the data directory
DATA_DIR = Path(__file__).parent.parent / "data"
DATA_DIR.mkdir(exist_ok=True)

print(f"Created data directory at: {DATA_DIR}")

# Create a README.md file in the data directory
with open(DATA_DIR / "README.md", 'w', encoding='utf-8') as f:
    f.write("""# Farmora AI Server Data Directory

This directory contains data files used by the Farmora AI Server:

- `markets_database.json`: Database of all states, districts, markets, and commodities from Agmarknet
- `geocoded_markets.json`: Geographical coordinates for markets

These files are generated by the `market_database_builder.py` script and used by the `geo_utils.py` module.
""")

print("Setup complete!")
